farm/farm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rup/', include('rup.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

farm/rup/urls.py
# from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import url
from django.contrib.auth import urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from . import views

app_name ='rup'
urlpatterns = [
    path('newfarm/', views.newfarm, name='newfarm.html'),
    path('polygon/', views.polygon, name='polygon.html'),
    path('get_product/', views.get_product, name='get_product'),
    path('modal/', views.modal, name='modal'),
    path('user_view/', views.user_view, name='user_view'),
    path('pick_center/', views.pick_center, name='pick_center'),
    path('mylogin/', views.mylogin, name='mylogin'),
    path('create_location/', views.create_location, name='create_location'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

farm/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login, {'template_name': 'login.html'}, name='login'),
    path('logout/', views.logout, {'next_page': 'login'}, name='logout'),
    path('register/', views.register, name='register'),
]

farm/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import logout
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model

def index(request):
    return render(request, 'index.html')

def dashboard(request):
    return render(request, 'dashboard.html')

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('rup:newfarm.html'))
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form':form})

farm/users/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Log in to My Site</h2>
  {% if form.errors %}
    <p style="color: red">Your username and password didn't match. Please try again.</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}<br>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% if field.help_text %}
          <p><small style="color: grey">{{ field.help_text }}</small></p>
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Log in</button>
    <a href="{% url 'users:register' %}">New to My Site? Sign up</a>
  </form>
{% endblock %}

farm/users/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Register{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      {% if user.is_authenticated %}
        <a href="{% url 'login' %}">logout</a> 
      {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'users:register' %}">signup</a>
      {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      <h1>Welcome Home, from Homepage</h1>
      {% endblock %}
    </main>
  </body>
</html>